nav:
  - Home: index.md
  - Initialization: 
    - To initialize a vehicle (GUI): Initialization/setup.md
    - To initialize a vehicle (API): Initialization/setup_api.md
    - Camara view: Initialization/camera.md
    - Navigation: Initialization/nav.md
    - Logs: Initialization/logs.md
  - Maintenance: 
      - Maintenance program: Maintenance/index.md
      - Tips and tricks: Maintenance/tips.md
  - Specifications: Specifications/index.md

theme:
  name: material
  features:
    - navigation.tabs      
    - navigation.top        
    - search.highlight     
    - toc.integrate         
    - content.code.copy
  palette:
    - primary: blue 

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences 
  - admonition  
  - pymdownx.details  

site_name: Muber Operating Guide